"""Risk-band constants and the runtime loader for the derived
base-risk table.

The four ordinal bands match `evaluation/prediction.py::RiskLevel`. Lower
ordinals are less severe; the rank mapping is the canonical comparison
key for over- vs under-escalation arithmetic in the derivation script
(issue #13) and the validator-gate trigger (#15).

This module's runtime API is consumed by:
- agent/nodes/risk.py (#14): `base_risk_for(subcategory)` is the
  starting prior the modifier-scoring node nudges with caller cues.
- agent/nodes/validator.py (#16) via #15's policy: the
  `intake_over_escalation_rate` per subcategory tells the validator
  whether to second-guess a confident classification.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable, Mapping, Optional, Tuple


RISK_LEVELS: Tuple[str, ...] = ("LOW", "MEDIUM", "HIGH", "EMERGENCY")
RISK_LEVEL_RANK: Mapping[str, int] = {lvl: i for i, lvl in enumerate(RISK_LEVELS)}

# `agent/data/derived/base_risk_by_subcategory.json` is generated by
# `scripts/derive_risk_bands.py` and committed. The runtime loader reads
# it at first call and caches.
_DERIVED_PATH: Path = (
    Path(__file__).resolve().parent / "derived" / "base_risk_by_subcategory.json"
)

_TABLE_CACHE: Optional[Dict[str, dict]] = None


def _load() -> Dict[str, dict]:
    if not _DERIVED_PATH.exists():
        raise RuntimeError(
            f"Derived risk table not found at {_DERIVED_PATH}. "
            "Run `python scripts/derive_risk_bands.py` to generate it."
        )
    return json.loads(_DERIVED_PATH.read_text())


def _table() -> Dict[str, dict]:
    global _TABLE_CACHE
    if _TABLE_CACHE is None:
        _TABLE_CACHE = _load()
    return _TABLE_CACHE


def is_valid_risk_level(level: str) -> bool:
    return level in RISK_LEVEL_RANK


def compare_risk(a: str, b: str) -> int:
    """Return positive if `a` is more severe than `b`, negative if less, 0 if equal.

    Raises KeyError on unknown levels.
    """
    return RISK_LEVEL_RANK[a] - RISK_LEVEL_RANK[b]


def base_risk_for(subcategory: Optional[str]) -> Optional[str]:
    """Modal risk level for a subcategory based on the historical corpus.

    Returns None when the subcategory isn't in the derived table — that
    only happens for synthetic / unseen subcategories the historicals
    never saw, in which case #14 should fall back to a conservative
    default like MEDIUM.
    """
    if not subcategory:
        return None
    entry = _table().get(subcategory)
    return entry["modal_risk"] if entry else None


def risk_distribution(subcategory: Optional[str]) -> Optional[Dict[str, float]]:
    """Distribution over LOW/MEDIUM/HIGH/EMERGENCY for a subcategory.

    Values are 0..1 and sum to 1. Useful for weighted-average risk
    calculations and for confidence calibration in #14.
    """
    if not subcategory:
        return None
    entry = _table().get(subcategory)
    return dict(entry["distribution"]) if entry else None


def intake_over_escalation_rate(subcategory: Optional[str]) -> float:
    """Fraction of historical tickets in this subcategory where intake
    risk was HIGHER than the on-site technician's final risk.

    Used by issue #15 to decide which subcategories' classifications need
    extra scrutiny from the validator gate. A high rate here means
    intake operators have historically over-stated severity for this
    issue type, so the agent should be skeptical of high-risk classifications.
    """
    if not subcategory:
        return 0.0
    entry = _table().get(subcategory)
    return float(entry.get("intake_over_escalation_rate", 0.0)) if entry else 0.0


def intake_under_escalation_rate(subcategory: Optional[str]) -> float:
    """Fraction of tickets where intake risk was LOWER than final.

    The mirror metric to over-escalation; used by #15 to flag
    subcategories where intake has historically MISSED severity.
    """
    if not subcategory:
        return 0.0
    entry = _table().get(subcategory)
    return float(entry.get("intake_under_escalation_rate", 0.0)) if entry else 0.0


def all_subcategories_in_table() -> Iterable[str]:
    """Subcategory keys present in the derived table.

    Should be a superset of `agent.data.taxonomy.all_subcategories()` so
    that the classifier never picks a label without a base risk on file.
    """
    return _table().keys()


def _reset_cache_for_tests() -> None:
    global _TABLE_CACHE
    _TABLE_CACHE = None
