"""Security hardening module — prompt injection detection and sanitization.

Defends against OWASP Agentic Threats:
  T6 (Intent Breaking) — detect injection patterns in caller transcripts
  T1 (Memory Poisoning) — sanitize trainer log content before storage
  T2 (Tool Misuse) — flag suspicious urgency cue fabrication
  T3 (Privilege Compromise) — detect cross-caller data leakage attempts

The detection layer runs BEFORE LLM calls and produces a `SecurityScan`
result that downstream nodes (validator gate, trainer log) consume.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

_INJECTION_PATTERNS: Tuple[re.Pattern, ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in (
        r"ignore\s+(all\s+)?(previous|prior|above)\s+(instructions?|prompts?|rules?|context)",
        r"disregard\s+(all\s+|your\s+)?(previous|prior|above|your)\s+(instructions?|prompts?|rules?)",
        r"forget\s+(all\s+|your\s+)?(previous|prior|above|your)\s+(instructions?|prompts?|rules?)",
        r"you\s+are\s+now\s+(?:a|an|my)\s+(?!tenant|caller|agent)",
        r"new\s+instructions?:\s*",
        r"system\s*(?:prompt|message)\s*:",
        r"<\s*/?system\s*>",
        r"\[\s*(?:SYSTEM|INST|ADMIN)\s*\]",
        r"(?:output|print|show|display|reveal|list)\s+(?:all\s+)?(?:caller|tenant|vendor|building)\s+(?:profiles?|data|records?|information)",
        r"(?:output|print|show|display|reveal)\s+(?:the\s+)?(?:system\s+)?prompt",
        r"(?:what|tell\s+me)\s+(?:are\s+)?your\s+(?:instructions|rules|system\s+prompt)",
        r"act\s+as\s+(?:if\s+you\s+(?:are|were)|a\s+)",
        r"pretend\s+(?:you\s+are|to\s+be)\s+",
        r"jailbreak",
        r"DAN\s+mode",
        r"do\s+anything\s+now",
        r"(?:override|bypass)\s+(?:all\s+)?(?:safety|security|restrictions?|filters?|rules?)",
    )
)

_DATA_EXFIL_PATTERNS: Tuple[re.Pattern, ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in (
        r"(?:list|show|give|tell)\s+(?:me\s+)?(?:all\s+)?(?:other\s+)?(?:callers?|tenants?|phone\s+numbers?|profiles?)",
        r"(?:what|who)\s+(?:other\s+)?(?:callers?|tenants?)\s+(?:are|have|called)",
        r"(?:access|read|dump|export)\s+(?:the\s+)?(?:database|json|records?|historical)",
        r"(?:how\s+many|count)\s+(?:callers?|tenants?|buildings?|vendors?)\s+(?:are|do\s+you\s+have)",
        r"vendor.*(?:phone|email|contact)",
    )
)

_ROLE_HIJACK_PATTERNS: Tuple[re.Pattern, ...] = tuple(
    re.compile(p, re.IGNORECASE) for p in (
        r"you\s+(?:are|will\s+be)\s+(?:now\s+)?(?:a\s+)?(?:helpful|friendly|concierge|assistant|chatbot)",
        r"(?:from\s+now\s+on|henceforth),?\s+(?:you|your)",
        r"(?:respond|reply|answer)\s+(?:only\s+)?(?:in|with)\s+(?:json|python|code|markdown)",
        r"(?:end|finish|conclude)\s+(?:every|each|all)\s+(?:reply|response|message)\s+with",
    )
)


@dataclass(frozen=True)
class SecurityScan:
    """Result of scanning caller turns for injection/exfiltration attempts."""
    injection_detected: bool
    exfiltration_detected: bool
    role_hijack_detected: bool
    matched_patterns: Tuple[str, ...] = field(default_factory=tuple)

    @property
    def any_threat(self) -> bool:
        return self.injection_detected or self.exfiltration_detected or self.role_hijack_detected

    @property
    def reasons(self) -> Tuple[str, ...]:
        reasons = []
        if self.injection_detected:
            reasons.append("security:prompt_injection_detected")
        if self.exfiltration_detected:
            reasons.append("security:data_exfiltration_attempt")
        if self.role_hijack_detected:
            reasons.append("security:role_hijack_attempt")
        return tuple(reasons)


def scan_turns(turns: List[dict]) -> SecurityScan:
    """Scan caller turns for prompt injection and data exfiltration patterns.

    Only scans caller speech — agent turns are trusted (generated by our system).
    """
    caller_text = " ".join(
        t.get("text", "") for t in turns if t.get("speaker") == "caller"
    )

    injection = False
    exfiltration = False
    role_hijack = False
    matched: List[str] = []

    for pat in _INJECTION_PATTERNS:
        m = pat.search(caller_text)
        if m:
            injection = True
            matched.append(f"injection:{m.group(0)[:60]}")
            break

    for pat in _DATA_EXFIL_PATTERNS:
        m = pat.search(caller_text)
        if m:
            exfiltration = True
            matched.append(f"exfil:{m.group(0)[:60]}")
            break

    for pat in _ROLE_HIJACK_PATTERNS:
        m = pat.search(caller_text)
        if m:
            role_hijack = True
            matched.append(f"hijack:{m.group(0)[:60]}")
            break

    return SecurityScan(
        injection_detected=injection,
        exfiltration_detected=exfiltration,
        role_hijack_detected=role_hijack,
        matched_patterns=tuple(matched),
    )


def sanitize_for_storage(text: str) -> str:
    """Strip known injection patterns from text before writing to trainer log.

    Replaces matched injection fragments with a safe placeholder so the
    stored transcript can't poison future fine-tuning pipelines (T1 defense).
    """
    sanitized = text
    all_patterns = _INJECTION_PATTERNS + _DATA_EXFIL_PATTERNS + _ROLE_HIJACK_PATTERNS
    for pat in all_patterns:
        sanitized = pat.sub("[REDACTED:security]", sanitized)
    return sanitized


def validate_extraction_output(
    extraction_building: Optional[str],
    extraction_floor: Optional[str],
    caller_phone: Optional[str],
    turns: List[dict],
) -> List[str]:
    """Post-LLM output validation — detect cross-caller data leakage.

    Checks that extracted fields are grounded in either the caller's
    transcript or their own profile. Flags anomalies where the LLM
    may have been manipulated into surfacing data from other callers.

    Returns a list of warning strings (empty = clean).
    """
    warnings: List[str] = []

    caller_text = " ".join(
        t.get("text", "") for t in turns if t.get("speaker") == "caller"
    )
    all_text = " ".join(t.get("text", "") for t in turns)

    if extraction_building and len(extraction_building) > 5:
        building_lower = extraction_building.lower()
        if (building_lower not in all_text.lower()
                and building_lower not in caller_text.lower()):
            from agent.data import profiles as prof_mod
            profile = prof_mod.lookup(caller_phone)
            profile_building = (
                (profile.primary_building_name or "").lower() if profile else ""
            )
            if building_lower != profile_building:
                warnings.append(
                    f"output_anomaly:building '{extraction_building}' not in transcript or profile"
                )

    return warnings
